import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, keepPreviousData } from "@tanstack/react-query";
import { useState, useMemo } from "react";
import {
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  Clock,
  Dna,
  FileEdit,
  HeartHandshake,
  Search,
  ShieldAlert,
  Shuffle,
  Stethoscope,
  Users,
  Waves,
} from "lucide-react";
import { api } from "@/services/api";
import { useAuth } from "@/lib/auth-context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { TelemetryRefreshButton } from "@/components/ui/telemetry-refresh-button";
import { StatusBadge, fmtDateTime } from "@/components/ui-kit";
import type { DoctorMatchProposal } from "@/services/types";

export const Route = createFileRoute("/_authed/doctor/matches/")({
  head: () => ({
    meta: [{ title: "Match Medical Reviews — OrganMatch" }],
  }),
  component: DoctorMatchesIndexPage,
});

function DoctorMatchesIndexPage() {
  const { user, ready } = useAuth();
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const [organFilter, setOrganFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  const {
    data: matches,
    isLoading,
    isFetching,
    error,
    refetch,
  } = useQuery({
    queryKey: ["doctor", "matches"],
    queryFn: () => api.doctorListMatches(),
    enabled: ready && !!user,
    refetchInterval: 15000,
    placeholderData: keepPreviousData,
  });

  const filteredMatches = useMemo(() => {
    return (matches ?? []).filter((m: DoctorMatchProposal) => {
      if (organFilter !== "all" && m.organ_type !== organFilter) return false;
      if (statusFilter !== "all") {
        if (statusFilter === "PENDING" && m.status !== "PENDING" && m.status !== "NEEDS_REVIEW") return false;
        if (statusFilter === "APPROVED" && m.status !== "APPROVED") return false;
        if (statusFilter === "NOT_APPROVED" && m.status !== "NOT_APPROVED") return false;
      }

      const q = search.toLowerCase().trim();
      if (!q) return true;
      return (
        m.match_code?.toLowerCase().includes(q) ||
        m.id?.toLowerCase().includes(q) ||
        m.donor_code?.toLowerCase().includes(q) ||
        m.recipient_code?.toLowerCase().includes(q) ||
        m.recipient_name?.toLowerCase().includes(q) ||
        m.organ_type?.toLowerCase().includes(q) ||
        m.donor_blood_group?.toLowerCase().includes(q) ||
        m.recipient_blood_group?.toLowerCase().includes(q)
      );
    });
  }, [matches, organFilter, statusFilter, search]);

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-5">
        <div>
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-purple-600/10 text-purple-600 flex items-center justify-center shadow-xs">
              <Shuffle className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Match Medical Reviews</h1>
              <p className="text-sm text-slate-500 mt-0.5 font-normal">
                Review compatibility recommendations generated by the matching engine before allocation authority review.
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <TelemetryRefreshButton
            label="Refresh Matches"
            onRefresh={() => refetch()}
            isFetching={isFetching}
          />
          <Link to="/doctor/assessments">
            <Button variant="outline" size="sm" className="gap-1.5 text-xs font-semibold">
              Clinical Assessments
            </Button>
          </Link>
          <Link to="/doctor/history">
            <Button variant="outline" size="sm" className="gap-1.5 text-xs font-semibold">
              <Clock className="h-4 w-4 text-slate-500" />
              Review History
            </Button>
          </Link>
        </div>
      </div>

      {/* Safety Notice Banner */}
      <div className="p-4 bg-amber-50/90 border border-amber-200/90 rounded-xl flex items-start gap-3.5 text-amber-950 text-sm shadow-xs">
        <ShieldAlert className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
        <div className="flex-1">
          <span className="font-semibold text-amber-900 block text-[13px]">
            Physician Clinical Mandate
          </span>
          <p className="text-xs text-amber-800/90 mt-0.5 leading-relaxed">
            Doctors provide clinical evaluation and recommendations. <strong>Final allocation decisions are handled by the Allocation Authority.</strong> Clear match suitability or request further HLA testing before allocation finalization.
          </p>
        </div>
      </div>

      {/* Search & Filter Bar */}
      <div className="flex flex-wrap items-center gap-3 p-4 bg-slate-50/70 border border-slate-200/80 rounded-xl">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by match ID, donor, recipient, blood group, organ..."
            className="pl-9 bg-white text-xs h-9 border-slate-200 shadow-2xs"
          />
        </div>

        <Select value={organFilter} onValueChange={setOrganFilter}>
          <SelectTrigger className="w-36 bg-white text-xs h-9 border-slate-200 shadow-2xs">
            <SelectValue placeholder="Organ Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Organs</SelectItem>
            <SelectItem value="KIDNEY">Kidney</SelectItem>
            <SelectItem value="HEART">Heart</SelectItem>
            <SelectItem value="LUNG">Lung</SelectItem>
            <SelectItem value="LIVER">Liver</SelectItem>
          </SelectContent>
        </Select>

        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-40 bg-white text-xs h-9 border-slate-200 shadow-2xs">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="PENDING">Pending Review</SelectItem>
            <SelectItem value="APPROVED">Suitable / Approved</SelectItem>
            <SelectItem value="NEEDS_REVIEW">Needs Review</SelectItem>
            <SelectItem value="NOT_APPROVED">Not Suitable</SelectItem>
          </SelectContent>
        </Select>

        {(search || organFilter !== "all" || statusFilter !== "all") && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              setSearch("");
              setOrganFilter("all");
              setStatusFilter("all");
            }}
            className="text-xs text-slate-500 hover:text-slate-900"
          >
            Clear Filters
          </Button>
        )}
      </div>

      {/* Matches Table */}
      <div className="bg-white border border-slate-200/80 rounded-xl shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-slate-50/80 border-b border-slate-200">
              <tr>
                {["MATCH ID", "DONOR", "RECIPIENT", "ORGAN", "COMPATIBILITY", "RANK", "PRIORITY", "STATUS", "NEXT STEP", "ACTION"].map((h) => (
                  <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {isLoading ? (
                <tr>
                  <td colSpan={10} className="px-6 py-12 text-center text-xs text-slate-400">
                    Loading match proposals…
                  </td>
                </tr>
              ) : error ? (
                <tr>
                  <td colSpan={10} className="px-6 py-12 text-center text-xs text-rose-600 font-medium">
                    Failed to load match reviews from server.
                  </td>
                </tr>
              ) : filteredMatches.length === 0 ? (
                <tr>
                  <td colSpan={10} className="px-6 py-12 text-center text-xs text-slate-400">
                    No active match proposals pending review.
                  </td>
                </tr>
              ) : (
                filteredMatches.map((m: DoctorMatchProposal) => {
                  const score = typeof m.compatibility_score === "number" ? Math.round(m.compatibility_score) : 0;
                  const isApproved = m.status === "APPROVED" || m.status === "SUITABLE";
                  const isRejected = m.status === "NOT_APPROVED" || m.status === "REJECTED";

                  return (
                    <tr key={m.id} className="hover:bg-slate-50/60 transition-colors">
                      {/* MATCH ID */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <span className="font-mono font-bold text-xs text-slate-900 bg-slate-100 px-2 py-1 rounded-md border border-slate-200">
                          {m.match_code || (m.id ? `MAT-${String(m.id).slice(0, 6).toUpperCase()}` : "MAT-PROPOSAL")}
                        </span>
                      </td>

                      {/* DONOR */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <div className="flex flex-col">
                          <span className="font-bold text-xs text-slate-900">
                            {m.donor_name || m.donor_code || "DNR"}
                          </span>
                          <span className="text-[11px] text-slate-500 font-mono">
                            {m.donor_code} • {m.donor_blood_group || "—"}
                          </span>
                        </div>
                      </td>

                      {/* RECIPIENT */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <div className="flex flex-col">
                          <span className="font-bold text-xs text-slate-900">
                            {m.recipient_name || m.recipient_code || "REC"}
                          </span>
                          <span className="text-[11px] text-slate-500 font-mono">
                            {m.recipient_code} • {m.recipient_blood_group || "—"}
                          </span>
                        </div>
                      </td>

                      {/* ORGAN */}
                      <td className="px-5 py-3.5 whitespace-nowrap font-medium text-slate-800 text-xs">
                        {m.organ_type}
                      </td>

                      {/* COMPATIBILITY */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <Badge
                          className={`font-mono text-xs font-bold ${
                            score >= 85
                              ? "bg-emerald-600 text-white"
                              : score >= 70
                              ? "bg-blue-600 text-white"
                              : "bg-amber-600 text-white"
                          }`}
                        >
                          {score}%
                        </Badge>
                      </td>

                      {/* RANK */}
                      <td className="px-5 py-3.5 whitespace-nowrap font-mono text-xs font-bold text-slate-800">
                        Rank #{m.rank || 1}
                      </td>

                      {/* PRIORITY */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <Badge
                          variant="outline"
                          className={
                            m.recipient_priority === "HIGH" || m.recipient_urgency === "CRITICAL"
                              ? "bg-rose-50 text-rose-700 border-rose-200 text-xs font-bold"
                              : "bg-slate-50 text-slate-700 border-slate-200 text-xs font-medium"
                          }
                        >
                          {m.recipient_urgency || m.recipient_priority || "Medium"}
                        </Badge>
                      </td>

                      {/* STATUS */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <StatusBadge value={m.status || "PENDING"} />
                      </td>

                      {/* NEXT STEP */}
                      <td className="px-5 py-3.5 whitespace-nowrap">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium border ${
                          isApproved
                            ? "bg-blue-50 text-blue-700 border-blue-200"
                            : isRejected
                            ? "bg-rose-50 text-rose-700 border-rose-200"
                            : "bg-slate-100 text-slate-700 border-slate-200"
                        }`}>
                          {isApproved
                            ? "Awaiting Allocation Authority"
                            : isRejected
                            ? "Review Rejected"
                            : "Doctor Clinical Review"}
                        </span>
                      </td>

                      {/* ACTION */}
                      <td className="px-5 py-3.5 whitespace-nowrap text-right">
                        <Link to={`/doctor/matching/${m.id}`}>
                          <Button size="sm" className="gap-1.5 text-xs font-semibold h-8 shadow-2xs bg-blue-600 hover:bg-blue-700 text-white">
                            <Stethoscope className="h-3.5 w-3.5" />
                            Review Match
                          </Button>
                        </Link>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
