import uuid
from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class OrganBase(BaseModel):
    donor_id: uuid.UUID = Field(..., description="ID of the donor this organ is harvested from")
    organ_type: str = Field(..., description="Type of organ: HEART, LUNG, KIDNEY, PANCREAS, LIVER")
    blood_group: str = Field(..., description="Donor's blood group")
    medical_details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Medical particulars (ischemia time, preservation method, etc.)"
    )


class OrganCreate(OrganBase):
    # organ_code is optional — backend auto-generates if omitted
    organ_code: Optional[str] = Field(
        None,
        description="Unique organ code. Auto-generated by backend if not supplied."
    )

    # Clinical fields — stored inside medical_details JSON on the backend
    laterality: Optional[str] = Field(
        None,
        description="Laterality for paired organs: LEFT, RIGHT, BOTH, N/A"
    )
    harvested_at: Optional[str] = Field(
        None,
        description="ISO-8601 datetime of harvest (e.g. 2026-08-28T10:45:00)"
    )
    warm_ischemia_minutes: Optional[int] = Field(
        None,
        ge=0,
        description="Warm ischemia time in minutes"
    )
    cold_ischemia_time: Optional[str] = Field(
        None,
        description="Cold ischemia time as HH:MM string"
    )
    preservation_method: Optional[str] = Field(
        None,
        description="Preservation method used (e.g. Static Cold Storage)"
    )
    clinical_notes: Optional[str] = Field(
        None,
        max_length=1000,
        description="Clinical/warm ischemia information"
    )
    additional_notes: Optional[str] = Field(
        None,
        max_length=500,
        description="Additional optional notes"
    )
    organ_status: Optional[str] = Field(
        None,
        description="Initial organ status: AVAILABLE or UNDER_REVIEW"
    )


class OrganUpdate(BaseModel):
    medical_details: Optional[Dict[str, Any]] = None
    status: Optional[str] = Field(
        None,
        description="Status: AVAILABLE, UNDER_REVIEW, MATCHED, ALLOCATED, UNAVAILABLE"
    )


class OrganDonorSummary(BaseModel):
    id: uuid.UUID
    donor_code: str
    name: Optional[str] = None
    age: int
    blood_group: str
    hospital_id: Optional[uuid.UUID] = None

    class Config:
        from_attributes = True



class OrganResponse(OrganBase):
    id: uuid.UUID
    organ_code: str
    status: str
    ischemic_start_time: Optional[datetime] = None
    max_ischemic_hours: Optional[int] = None
    donor: Optional[OrganDonorSummary] = None
    created_by: uuid.UUID
    updated_by: uuid.UUID
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
