/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed.admin.index'
import { Route as AuthedAllocationIndexRouteImport } from './routes/_authed.allocation.index'
import { Route as AuthedAllocationsIndexRouteImport } from './routes/_authed.allocations.index'
import { Route as AuthedBlockchainIndexRouteImport } from './routes/_authed.blockchain.index'
import { Route as AuthedCoordinatorIndexRouteImport } from './routes/_authed.coordinator.index'
import { Route as AuthedDoctorIndexRouteImport } from './routes/_authed.doctor.index'
import { Route as AuthedDonorsIndexRouteImport } from './routes/_authed.donors.index'
import { Route as AuthedDonorsDonorIdRouteImport } from './routes/_authed.donors.$donorId'
import { Route as AuthedDonorsNewRouteImport } from './routes/_authed.donors.new'
import { Route as AuthedHospitalsIndexRouteImport } from './routes/_authed.hospitals.index'
import { Route as AuthedMatchingIndexRouteImport } from './routes/_authed.matching.index'
import { Route as AuthedOrgansIndexRouteImport } from './routes/_authed.organs.index'
import { Route as AuthedPermissionsIndexRouteImport } from './routes/_authed.permissions.index'
import { Route as AuthedRecipientsIndexRouteImport } from './routes/_authed.recipients.index'
import { Route as AuthedRecipientsRecipientIdRouteImport } from './routes/_authed.recipients.$recipientId'
import { Route as AuthedRecipientsNewRouteImport } from './routes/_authed.recipients.new'
import { Route as AuthedSecurityEventIdRouteImport } from './routes/_authed.security.$eventId'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed.settings.index'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed.users.index'
import { Route as AuthedAdminBlockchainIndexRouteImport } from './routes/_authed.admin.blockchain.index'
import { Route as AuthedAdminHospitalsIndexRouteImport } from './routes/_authed.admin.hospitals.index'
import { Route as AuthedAdminMonitoringIndexRouteImport } from './routes/_authed.admin.monitoring.index'
import { Route as AuthedAdminRolesIndexRouteImport } from './routes/_authed.admin.roles.index'
import { Route as AuthedAdminSettingsIndexRouteImport } from './routes/_authed.admin.settings.index'
import { Route as AuthedAdminTamperingIndexRouteImport } from './routes/_authed.admin.tampering.index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed.admin.users.index'
import { Route as AuthedAllocationHistoryIndexRouteImport } from './routes/_authed.allocation.history.index'
import { Route as AuthedAllocationMatchesIndexRouteImport } from './routes/_authed.allocation.matches.index'
import { Route as AuthedAllocationMatchesMatchIdRouteImport } from './routes/_authed.allocation.matches.$matchId'
import { Route as AuthedAllocationOrgansIndexRouteImport } from './routes/_authed.allocation.organs.index'
import { Route as AuthedAllocationQueueIndexRouteImport } from './routes/_authed.allocation.queue.index'
import { Route as AuthedCoordinatorAllocationsIndexRouteImport } from './routes/_authed.coordinator.allocations.index'
import { Route as AuthedCoordinatorDonorsIndexRouteImport } from './routes/_authed.coordinator.donors.index'
import { Route as AuthedCoordinatorDonorsDonorIdRouteImport } from './routes/_authed.coordinator.donors.$donorId'
import { Route as AuthedCoordinatorDonorsNewRouteImport } from './routes/_authed.coordinator.donors.new'
import { Route as AuthedCoordinatorMatchingIndexRouteImport } from './routes/_authed.coordinator.matching.index'
import { Route as AuthedCoordinatorOrgansIndexRouteImport } from './routes/_authed.coordinator.organs.index'
import { Route as AuthedCoordinatorOrgansNewRouteImport } from './routes/_authed.coordinator.organs.new'
import { Route as AuthedCoordinatorRecipientsIndexRouteImport } from './routes/_authed.coordinator.recipients.index'
import { Route as AuthedCoordinatorRecipientsRecipientIdRouteImport } from './routes/_authed.coordinator.recipients.$recipientId'
import { Route as AuthedCoordinatorRecipientsNewRouteImport } from './routes/_authed.coordinator.recipients.new'
import { Route as AuthedDoctorAssessmentsIndexRouteImport } from './routes/_authed.doctor.assessments.index'
import { Route as AuthedDoctorAssessmentsAssessmentIdRouteImport } from './routes/_authed.doctor.assessments.$assessmentId'
import { Route as AuthedDoctorDonorsIndexRouteImport } from './routes/_authed.doctor.donors.index'
import { Route as AuthedDoctorDonorsDonorIdRouteImport } from './routes/_authed.doctor.donors.$donorId'
import { Route as AuthedDoctorHistoryIndexRouteImport } from './routes/_authed.doctor.history.index'
import { Route as AuthedDoctorMatchesIndexRouteImport } from './routes/_authed.doctor.matches.index'
import { Route as AuthedDoctorMatchesMatchIdRouteImport } from './routes/_authed.doctor.matches.$matchId'
import { Route as AuthedDoctorMatchingIndexRouteImport } from './routes/_authed.doctor.matching.index'
import { Route as AuthedDoctorMatchingMatchIdRouteImport } from './routes/_authed.doctor.matching.$matchId'
import { Route as AuthedDoctorOrgansIndexRouteImport } from './routes/_authed.doctor.organs.index'
import { Route as AuthedDoctorOrgansOrganIdRouteImport } from './routes/_authed.doctor.organs.$organId'
import { Route as AuthedDoctorRecipientsIndexRouteImport } from './routes/_authed.doctor.recipients.index'
import { Route as AuthedDoctorRecipientsRecipientIdRouteImport } from './routes/_authed.doctor.recipients.$recipientId'
import { Route as AuthedAdminMonitoringApiActivityIndexRouteImport } from './routes/_authed.admin.monitoring.api-activity.index'
import { Route as AuthedAdminMonitoringAuthenticationIndexRouteImport } from './routes/_authed.admin.monitoring.authentication.index'
import { Route as AuthedAdminMonitoringBackendIndexRouteImport } from './routes/_authed.admin.monitoring.backend.index'
import { Route as AuthedAdminMonitoringBlockchainIndexRouteImport } from './routes/_authed.admin.monitoring.blockchain.index'
import { Route as AuthedAdminMonitoringDatabaseIndexRouteImport } from './routes/_authed.admin.monitoring.database.index'
import { Route as AuthedAdminMonitoringDockerIndexRouteImport } from './routes/_authed.admin.monitoring.docker.index'
import { Route as AuthedAdminMonitoringErrorsIndexRouteImport } from './routes/_authed.admin.monitoring.errors.index'
import { Route as AuthedAdminMonitoringFrontendIndexRouteImport } from './routes/_authed.admin.monitoring.frontend.index'
import { Route as AuthedAdminMonitoringPostgresqlIndexRouteImport } from './routes/_authed.admin.monitoring.postgresql.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllocationIndexRoute = AuthedAllocationIndexRouteImport.update({
  id: '/allocation/',
  path: '/allocation/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllocationsIndexRoute = AuthedAllocationsIndexRouteImport.update({
  id: '/allocations/',
  path: '/allocations/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBlockchainIndexRoute = AuthedBlockchainIndexRouteImport.update({
  id: '/blockchain/',
  path: '/blockchain/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCoordinatorIndexRoute = AuthedCoordinatorIndexRouteImport.update({
  id: '/coordinator/',
  path: '/coordinator/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDoctorIndexRoute = AuthedDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDonorsIndexRoute = AuthedDonorsIndexRouteImport.update({
  id: '/donors/',
  path: '/donors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDonorsDonorIdRoute = AuthedDonorsDonorIdRouteImport.update({
  id: '/donors/$donorId',
  path: '/donors/$donorId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDonorsNewRoute = AuthedDonorsNewRouteImport.update({
  id: '/donors/new',
  path: '/donors/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHospitalsIndexRoute = AuthedHospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMatchingIndexRoute = AuthedMatchingIndexRouteImport.update({
  id: '/matching/',
  path: '/matching/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgansIndexRoute = AuthedOrgansIndexRouteImport.update({
  id: '/organs/',
  path: '/organs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionsIndexRoute = AuthedPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipientsIndexRoute = AuthedRecipientsIndexRouteImport.update({
  id: '/recipients/',
  path: '/recipients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipientsRecipientIdRoute =
  AuthedRecipientsRecipientIdRouteImport.update({
    id: '/recipients/$recipientId',
    path: '/recipients/$recipientId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRecipientsNewRoute = AuthedRecipientsNewRouteImport.update({
  id: '/recipients/new',
  path: '/recipients/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecurityEventIdRoute = AuthedSecurityEventIdRouteImport.update({
  id: '/security/$eventId',
  path: '/security/$eventId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminBlockchainIndexRoute =
  AuthedAdminBlockchainIndexRouteImport.update({
    id: '/admin/blockchain/',
    path: '/admin/blockchain/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminHospitalsIndexRoute =
  AuthedAdminHospitalsIndexRouteImport.update({
    id: '/admin/hospitals/',
    path: '/admin/hospitals/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringIndexRoute =
  AuthedAdminMonitoringIndexRouteImport.update({
    id: '/admin/monitoring/',
    path: '/admin/monitoring/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminRolesIndexRoute = AuthedAdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSettingsIndexRoute =
  AuthedAdminSettingsIndexRouteImport.update({
    id: '/admin/settings/',
    path: '/admin/settings/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminTamperingIndexRoute =
  AuthedAdminTamperingIndexRouteImport.update({
    id: '/admin/tampering/',
    path: '/admin/tampering/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllocationHistoryIndexRoute =
  AuthedAllocationHistoryIndexRouteImport.update({
    id: '/allocation/history/',
    path: '/allocation/history/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAllocationMatchesIndexRoute =
  AuthedAllocationMatchesIndexRouteImport.update({
    id: '/allocation/matches/',
    path: '/allocation/matches/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAllocationMatchesMatchIdRoute =
  AuthedAllocationMatchesMatchIdRouteImport.update({
    id: '/allocation/matches/$matchId',
    path: '/allocation/matches/$matchId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAllocationOrgansIndexRoute =
  AuthedAllocationOrgansIndexRouteImport.update({
    id: '/allocation/organs/',
    path: '/allocation/organs/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAllocationQueueIndexRoute =
  AuthedAllocationQueueIndexRouteImport.update({
    id: '/allocation/queue/',
    path: '/allocation/queue/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorAllocationsIndexRoute =
  AuthedCoordinatorAllocationsIndexRouteImport.update({
    id: '/coordinator/allocations/',
    path: '/coordinator/allocations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorDonorsIndexRoute =
  AuthedCoordinatorDonorsIndexRouteImport.update({
    id: '/coordinator/donors/',
    path: '/coordinator/donors/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorDonorsDonorIdRoute =
  AuthedCoordinatorDonorsDonorIdRouteImport.update({
    id: '/coordinator/donors/$donorId',
    path: '/coordinator/donors/$donorId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorDonorsNewRoute =
  AuthedCoordinatorDonorsNewRouteImport.update({
    id: '/coordinator/donors/new',
    path: '/coordinator/donors/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorMatchingIndexRoute =
  AuthedCoordinatorMatchingIndexRouteImport.update({
    id: '/coordinator/matching/',
    path: '/coordinator/matching/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorOrgansIndexRoute =
  AuthedCoordinatorOrgansIndexRouteImport.update({
    id: '/coordinator/organs/',
    path: '/coordinator/organs/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorOrgansNewRoute =
  AuthedCoordinatorOrgansNewRouteImport.update({
    id: '/coordinator/organs/new',
    path: '/coordinator/organs/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorRecipientsIndexRoute =
  AuthedCoordinatorRecipientsIndexRouteImport.update({
    id: '/coordinator/recipients/',
    path: '/coordinator/recipients/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorRecipientsRecipientIdRoute =
  AuthedCoordinatorRecipientsRecipientIdRouteImport.update({
    id: '/coordinator/recipients/$recipientId',
    path: '/coordinator/recipients/$recipientId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCoordinatorRecipientsNewRoute =
  AuthedCoordinatorRecipientsNewRouteImport.update({
    id: '/coordinator/recipients/new',
    path: '/coordinator/recipients/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorAssessmentsIndexRoute =
  AuthedDoctorAssessmentsIndexRouteImport.update({
    id: '/doctor/assessments/',
    path: '/doctor/assessments/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorAssessmentsAssessmentIdRoute =
  AuthedDoctorAssessmentsAssessmentIdRouteImport.update({
    id: '/doctor/assessments/$assessmentId',
    path: '/doctor/assessments/$assessmentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorDonorsIndexRoute = AuthedDoctorDonorsIndexRouteImport.update({
  id: '/doctor/donors/',
  path: '/doctor/donors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDoctorDonorsDonorIdRoute =
  AuthedDoctorDonorsDonorIdRouteImport.update({
    id: '/doctor/donors/$donorId',
    path: '/doctor/donors/$donorId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorHistoryIndexRoute =
  AuthedDoctorHistoryIndexRouteImport.update({
    id: '/doctor/history/',
    path: '/doctor/history/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorMatchesIndexRoute =
  AuthedDoctorMatchesIndexRouteImport.update({
    id: '/doctor/matches/',
    path: '/doctor/matches/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorMatchesMatchIdRoute =
  AuthedDoctorMatchesMatchIdRouteImport.update({
    id: '/doctor/matches/$matchId',
    path: '/doctor/matches/$matchId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorMatchingIndexRoute =
  AuthedDoctorMatchingIndexRouteImport.update({
    id: '/doctor/matching/',
    path: '/doctor/matching/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorMatchingMatchIdRoute =
  AuthedDoctorMatchingMatchIdRouteImport.update({
    id: '/doctor/matching/$matchId',
    path: '/doctor/matching/$matchId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorOrgansIndexRoute = AuthedDoctorOrgansIndexRouteImport.update({
  id: '/doctor/organs/',
  path: '/doctor/organs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDoctorOrgansOrganIdRoute =
  AuthedDoctorOrgansOrganIdRouteImport.update({
    id: '/doctor/organs/$organId',
    path: '/doctor/organs/$organId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorRecipientsIndexRoute =
  AuthedDoctorRecipientsIndexRouteImport.update({
    id: '/doctor/recipients/',
    path: '/doctor/recipients/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDoctorRecipientsRecipientIdRoute =
  AuthedDoctorRecipientsRecipientIdRouteImport.update({
    id: '/doctor/recipients/$recipientId',
    path: '/doctor/recipients/$recipientId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringApiActivityIndexRoute =
  AuthedAdminMonitoringApiActivityIndexRouteImport.update({
    id: '/admin/monitoring/api-activity/',
    path: '/admin/monitoring/api-activity/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringAuthenticationIndexRoute =
  AuthedAdminMonitoringAuthenticationIndexRouteImport.update({
    id: '/admin/monitoring/authentication/',
    path: '/admin/monitoring/authentication/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringBackendIndexRoute =
  AuthedAdminMonitoringBackendIndexRouteImport.update({
    id: '/admin/monitoring/backend/',
    path: '/admin/monitoring/backend/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringBlockchainIndexRoute =
  AuthedAdminMonitoringBlockchainIndexRouteImport.update({
    id: '/admin/monitoring/blockchain/',
    path: '/admin/monitoring/blockchain/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringDatabaseIndexRoute =
  AuthedAdminMonitoringDatabaseIndexRouteImport.update({
    id: '/admin/monitoring/database/',
    path: '/admin/monitoring/database/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringDockerIndexRoute =
  AuthedAdminMonitoringDockerIndexRouteImport.update({
    id: '/admin/monitoring/docker/',
    path: '/admin/monitoring/docker/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringErrorsIndexRoute =
  AuthedAdminMonitoringErrorsIndexRouteImport.update({
    id: '/admin/monitoring/errors/',
    path: '/admin/monitoring/errors/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringFrontendIndexRoute =
  AuthedAdminMonitoringFrontendIndexRouteImport.update({
    id: '/admin/monitoring/frontend/',
    path: '/admin/monitoring/frontend/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMonitoringPostgresqlIndexRoute =
  AuthedAdminMonitoringPostgresqlIndexRouteImport.update({
    id: '/admin/monitoring/postgresql/',
    path: '/admin/monitoring/postgresql/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/donors/$donorId': typeof AuthedDonorsDonorIdRoute
  '/donors/new': typeof AuthedDonorsNewRoute
  '/recipients/$recipientId': typeof AuthedRecipientsRecipientIdRoute
  '/recipients/new': typeof AuthedRecipientsNewRoute
  '/security/$eventId': typeof AuthedSecurityEventIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/allocation/': typeof AuthedAllocationIndexRoute
  '/allocations/': typeof AuthedAllocationsIndexRoute
  '/blockchain/': typeof AuthedBlockchainIndexRoute
  '/coordinator/': typeof AuthedCoordinatorIndexRoute
  '/doctor/': typeof AuthedDoctorIndexRoute
  '/donors/': typeof AuthedDonorsIndexRoute
  '/hospitals/': typeof AuthedHospitalsIndexRoute
  '/matching/': typeof AuthedMatchingIndexRoute
  '/organs/': typeof AuthedOrgansIndexRoute
  '/permissions/': typeof AuthedPermissionsIndexRoute
  '/recipients/': typeof AuthedRecipientsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
  '/allocation/matches/$matchId': typeof AuthedAllocationMatchesMatchIdRoute
  '/coordinator/donors/$donorId': typeof AuthedCoordinatorDonorsDonorIdRoute
  '/coordinator/donors/new': typeof AuthedCoordinatorDonorsNewRoute
  '/coordinator/organs/new': typeof AuthedCoordinatorOrgansNewRoute
  '/coordinator/recipients/$recipientId': typeof AuthedCoordinatorRecipientsRecipientIdRoute
  '/coordinator/recipients/new': typeof AuthedCoordinatorRecipientsNewRoute
  '/doctor/assessments/$assessmentId': typeof AuthedDoctorAssessmentsAssessmentIdRoute
  '/doctor/donors/$donorId': typeof AuthedDoctorDonorsDonorIdRoute
  '/doctor/matches/$matchId': typeof AuthedDoctorMatchesMatchIdRoute
  '/doctor/matching/$matchId': typeof AuthedDoctorMatchingMatchIdRoute
  '/doctor/organs/$organId': typeof AuthedDoctorOrgansOrganIdRoute
  '/doctor/recipients/$recipientId': typeof AuthedDoctorRecipientsRecipientIdRoute
  '/admin/blockchain/': typeof AuthedAdminBlockchainIndexRoute
  '/admin/hospitals/': typeof AuthedAdminHospitalsIndexRoute
  '/admin/monitoring/': typeof AuthedAdminMonitoringIndexRoute
  '/admin/roles/': typeof AuthedAdminRolesIndexRoute
  '/admin/settings/': typeof AuthedAdminSettingsIndexRoute
  '/admin/tampering/': typeof AuthedAdminTamperingIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/allocation/history/': typeof AuthedAllocationHistoryIndexRoute
  '/allocation/matches/': typeof AuthedAllocationMatchesIndexRoute
  '/allocation/organs/': typeof AuthedAllocationOrgansIndexRoute
  '/allocation/queue/': typeof AuthedAllocationQueueIndexRoute
  '/coordinator/allocations/': typeof AuthedCoordinatorAllocationsIndexRoute
  '/coordinator/donors/': typeof AuthedCoordinatorDonorsIndexRoute
  '/coordinator/matching/': typeof AuthedCoordinatorMatchingIndexRoute
  '/coordinator/organs/': typeof AuthedCoordinatorOrgansIndexRoute
  '/coordinator/recipients/': typeof AuthedCoordinatorRecipientsIndexRoute
  '/doctor/assessments/': typeof AuthedDoctorAssessmentsIndexRoute
  '/doctor/donors/': typeof AuthedDoctorDonorsIndexRoute
  '/doctor/history/': typeof AuthedDoctorHistoryIndexRoute
  '/doctor/matches/': typeof AuthedDoctorMatchesIndexRoute
  '/doctor/matching/': typeof AuthedDoctorMatchingIndexRoute
  '/doctor/organs/': typeof AuthedDoctorOrgansIndexRoute
  '/doctor/recipients/': typeof AuthedDoctorRecipientsIndexRoute
  '/admin/monitoring/api-activity/': typeof AuthedAdminMonitoringApiActivityIndexRoute
  '/admin/monitoring/authentication/': typeof AuthedAdminMonitoringAuthenticationIndexRoute
  '/admin/monitoring/backend/': typeof AuthedAdminMonitoringBackendIndexRoute
  '/admin/monitoring/blockchain/': typeof AuthedAdminMonitoringBlockchainIndexRoute
  '/admin/monitoring/database/': typeof AuthedAdminMonitoringDatabaseIndexRoute
  '/admin/monitoring/docker/': typeof AuthedAdminMonitoringDockerIndexRoute
  '/admin/monitoring/errors/': typeof AuthedAdminMonitoringErrorsIndexRoute
  '/admin/monitoring/frontend/': typeof AuthedAdminMonitoringFrontendIndexRoute
  '/admin/monitoring/postgresql/': typeof AuthedAdminMonitoringPostgresqlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/donors/$donorId': typeof AuthedDonorsDonorIdRoute
  '/donors/new': typeof AuthedDonorsNewRoute
  '/recipients/$recipientId': typeof AuthedRecipientsRecipientIdRoute
  '/recipients/new': typeof AuthedRecipientsNewRoute
  '/security/$eventId': typeof AuthedSecurityEventIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/allocation': typeof AuthedAllocationIndexRoute
  '/allocations': typeof AuthedAllocationsIndexRoute
  '/blockchain': typeof AuthedBlockchainIndexRoute
  '/coordinator': typeof AuthedCoordinatorIndexRoute
  '/doctor': typeof AuthedDoctorIndexRoute
  '/donors': typeof AuthedDonorsIndexRoute
  '/hospitals': typeof AuthedHospitalsIndexRoute
  '/matching': typeof AuthedMatchingIndexRoute
  '/organs': typeof AuthedOrgansIndexRoute
  '/permissions': typeof AuthedPermissionsIndexRoute
  '/recipients': typeof AuthedRecipientsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/users': typeof AuthedUsersIndexRoute
  '/allocation/matches/$matchId': typeof AuthedAllocationMatchesMatchIdRoute
  '/coordinator/donors/$donorId': typeof AuthedCoordinatorDonorsDonorIdRoute
  '/coordinator/donors/new': typeof AuthedCoordinatorDonorsNewRoute
  '/coordinator/organs/new': typeof AuthedCoordinatorOrgansNewRoute
  '/coordinator/recipients/$recipientId': typeof AuthedCoordinatorRecipientsRecipientIdRoute
  '/coordinator/recipients/new': typeof AuthedCoordinatorRecipientsNewRoute
  '/doctor/assessments/$assessmentId': typeof AuthedDoctorAssessmentsAssessmentIdRoute
  '/doctor/donors/$donorId': typeof AuthedDoctorDonorsDonorIdRoute
  '/doctor/matches/$matchId': typeof AuthedDoctorMatchesMatchIdRoute
  '/doctor/matching/$matchId': typeof AuthedDoctorMatchingMatchIdRoute
  '/doctor/organs/$organId': typeof AuthedDoctorOrgansOrganIdRoute
  '/doctor/recipients/$recipientId': typeof AuthedDoctorRecipientsRecipientIdRoute
  '/admin/blockchain': typeof AuthedAdminBlockchainIndexRoute
  '/admin/hospitals': typeof AuthedAdminHospitalsIndexRoute
  '/admin/monitoring': typeof AuthedAdminMonitoringIndexRoute
  '/admin/roles': typeof AuthedAdminRolesIndexRoute
  '/admin/settings': typeof AuthedAdminSettingsIndexRoute
  '/admin/tampering': typeof AuthedAdminTamperingIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/allocation/history': typeof AuthedAllocationHistoryIndexRoute
  '/allocation/matches': typeof AuthedAllocationMatchesIndexRoute
  '/allocation/organs': typeof AuthedAllocationOrgansIndexRoute
  '/allocation/queue': typeof AuthedAllocationQueueIndexRoute
  '/coordinator/allocations': typeof AuthedCoordinatorAllocationsIndexRoute
  '/coordinator/donors': typeof AuthedCoordinatorDonorsIndexRoute
  '/coordinator/matching': typeof AuthedCoordinatorMatchingIndexRoute
  '/coordinator/organs': typeof AuthedCoordinatorOrgansIndexRoute
  '/coordinator/recipients': typeof AuthedCoordinatorRecipientsIndexRoute
  '/doctor/assessments': typeof AuthedDoctorAssessmentsIndexRoute
  '/doctor/donors': typeof AuthedDoctorDonorsIndexRoute
  '/doctor/history': typeof AuthedDoctorHistoryIndexRoute
  '/doctor/matches': typeof AuthedDoctorMatchesIndexRoute
  '/doctor/matching': typeof AuthedDoctorMatchingIndexRoute
  '/doctor/organs': typeof AuthedDoctorOrgansIndexRoute
  '/doctor/recipients': typeof AuthedDoctorRecipientsIndexRoute
  '/admin/monitoring/api-activity': typeof AuthedAdminMonitoringApiActivityIndexRoute
  '/admin/monitoring/authentication': typeof AuthedAdminMonitoringAuthenticationIndexRoute
  '/admin/monitoring/backend': typeof AuthedAdminMonitoringBackendIndexRoute
  '/admin/monitoring/blockchain': typeof AuthedAdminMonitoringBlockchainIndexRoute
  '/admin/monitoring/database': typeof AuthedAdminMonitoringDatabaseIndexRoute
  '/admin/monitoring/docker': typeof AuthedAdminMonitoringDockerIndexRoute
  '/admin/monitoring/errors': typeof AuthedAdminMonitoringErrorsIndexRoute
  '/admin/monitoring/frontend': typeof AuthedAdminMonitoringFrontendIndexRoute
  '/admin/monitoring/postgresql': typeof AuthedAdminMonitoringPostgresqlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/donors/$donorId': typeof AuthedDonorsDonorIdRoute
  '/_authed/donors/new': typeof AuthedDonorsNewRoute
  '/_authed/recipients/$recipientId': typeof AuthedRecipientsRecipientIdRoute
  '/_authed/recipients/new': typeof AuthedRecipientsNewRoute
  '/_authed/security/$eventId': typeof AuthedSecurityEventIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/allocation/': typeof AuthedAllocationIndexRoute
  '/_authed/allocations/': typeof AuthedAllocationsIndexRoute
  '/_authed/blockchain/': typeof AuthedBlockchainIndexRoute
  '/_authed/coordinator/': typeof AuthedCoordinatorIndexRoute
  '/_authed/doctor/': typeof AuthedDoctorIndexRoute
  '/_authed/donors/': typeof AuthedDonorsIndexRoute
  '/_authed/hospitals/': typeof AuthedHospitalsIndexRoute
  '/_authed/matching/': typeof AuthedMatchingIndexRoute
  '/_authed/organs/': typeof AuthedOrgansIndexRoute
  '/_authed/permissions/': typeof AuthedPermissionsIndexRoute
  '/_authed/recipients/': typeof AuthedRecipientsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
  '/_authed/allocation/matches/$matchId': typeof AuthedAllocationMatchesMatchIdRoute
  '/_authed/coordinator/donors/$donorId': typeof AuthedCoordinatorDonorsDonorIdRoute
  '/_authed/coordinator/donors/new': typeof AuthedCoordinatorDonorsNewRoute
  '/_authed/coordinator/organs/new': typeof AuthedCoordinatorOrgansNewRoute
  '/_authed/coordinator/recipients/$recipientId': typeof AuthedCoordinatorRecipientsRecipientIdRoute
  '/_authed/coordinator/recipients/new': typeof AuthedCoordinatorRecipientsNewRoute
  '/_authed/doctor/assessments/$assessmentId': typeof AuthedDoctorAssessmentsAssessmentIdRoute
  '/_authed/doctor/donors/$donorId': typeof AuthedDoctorDonorsDonorIdRoute
  '/_authed/doctor/matches/$matchId': typeof AuthedDoctorMatchesMatchIdRoute
  '/_authed/doctor/matching/$matchId': typeof AuthedDoctorMatchingMatchIdRoute
  '/_authed/doctor/organs/$organId': typeof AuthedDoctorOrgansOrganIdRoute
  '/_authed/doctor/recipients/$recipientId': typeof AuthedDoctorRecipientsRecipientIdRoute
  '/_authed/admin/blockchain/': typeof AuthedAdminBlockchainIndexRoute
  '/_authed/admin/hospitals/': typeof AuthedAdminHospitalsIndexRoute
  '/_authed/admin/monitoring/': typeof AuthedAdminMonitoringIndexRoute
  '/_authed/admin/roles/': typeof AuthedAdminRolesIndexRoute
  '/_authed/admin/settings/': typeof AuthedAdminSettingsIndexRoute
  '/_authed/admin/tampering/': typeof AuthedAdminTamperingIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/allocation/history/': typeof AuthedAllocationHistoryIndexRoute
  '/_authed/allocation/matches/': typeof AuthedAllocationMatchesIndexRoute
  '/_authed/allocation/organs/': typeof AuthedAllocationOrgansIndexRoute
  '/_authed/allocation/queue/': typeof AuthedAllocationQueueIndexRoute
  '/_authed/coordinator/allocations/': typeof AuthedCoordinatorAllocationsIndexRoute
  '/_authed/coordinator/donors/': typeof AuthedCoordinatorDonorsIndexRoute
  '/_authed/coordinator/matching/': typeof AuthedCoordinatorMatchingIndexRoute
  '/_authed/coordinator/organs/': typeof AuthedCoordinatorOrgansIndexRoute
  '/_authed/coordinator/recipients/': typeof AuthedCoordinatorRecipientsIndexRoute
  '/_authed/doctor/assessments/': typeof AuthedDoctorAssessmentsIndexRoute
  '/_authed/doctor/donors/': typeof AuthedDoctorDonorsIndexRoute
  '/_authed/doctor/history/': typeof AuthedDoctorHistoryIndexRoute
  '/_authed/doctor/matches/': typeof AuthedDoctorMatchesIndexRoute
  '/_authed/doctor/matching/': typeof AuthedDoctorMatchingIndexRoute
  '/_authed/doctor/organs/': typeof AuthedDoctorOrgansIndexRoute
  '/_authed/doctor/recipients/': typeof AuthedDoctorRecipientsIndexRoute
  '/_authed/admin/monitoring/api-activity/': typeof AuthedAdminMonitoringApiActivityIndexRoute
  '/_authed/admin/monitoring/authentication/': typeof AuthedAdminMonitoringAuthenticationIndexRoute
  '/_authed/admin/monitoring/backend/': typeof AuthedAdminMonitoringBackendIndexRoute
  '/_authed/admin/monitoring/blockchain/': typeof AuthedAdminMonitoringBlockchainIndexRoute
  '/_authed/admin/monitoring/database/': typeof AuthedAdminMonitoringDatabaseIndexRoute
  '/_authed/admin/monitoring/docker/': typeof AuthedAdminMonitoringDockerIndexRoute
  '/_authed/admin/monitoring/errors/': typeof AuthedAdminMonitoringErrorsIndexRoute
  '/_authed/admin/monitoring/frontend/': typeof AuthedAdminMonitoringFrontendIndexRoute
  '/_authed/admin/monitoring/postgresql/': typeof AuthedAdminMonitoringPostgresqlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/donors/$donorId'
    | '/donors/new'
    | '/recipients/$recipientId'
    | '/recipients/new'
    | '/security/$eventId'
    | '/admin/'
    | '/allocation/'
    | '/allocations/'
    | '/blockchain/'
    | '/coordinator/'
    | '/doctor/'
    | '/donors/'
    | '/hospitals/'
    | '/matching/'
    | '/organs/'
    | '/permissions/'
    | '/recipients/'
    | '/settings/'
    | '/users/'
    | '/allocation/matches/$matchId'
    | '/coordinator/donors/$donorId'
    | '/coordinator/donors/new'
    | '/coordinator/organs/new'
    | '/coordinator/recipients/$recipientId'
    | '/coordinator/recipients/new'
    | '/doctor/assessments/$assessmentId'
    | '/doctor/donors/$donorId'
    | '/doctor/matches/$matchId'
    | '/doctor/matching/$matchId'
    | '/doctor/organs/$organId'
    | '/doctor/recipients/$recipientId'
    | '/admin/blockchain/'
    | '/admin/hospitals/'
    | '/admin/monitoring/'
    | '/admin/roles/'
    | '/admin/settings/'
    | '/admin/tampering/'
    | '/admin/users/'
    | '/allocation/history/'
    | '/allocation/matches/'
    | '/allocation/organs/'
    | '/allocation/queue/'
    | '/coordinator/allocations/'
    | '/coordinator/donors/'
    | '/coordinator/matching/'
    | '/coordinator/organs/'
    | '/coordinator/recipients/'
    | '/doctor/assessments/'
    | '/doctor/donors/'
    | '/doctor/history/'
    | '/doctor/matches/'
    | '/doctor/matching/'
    | '/doctor/organs/'
    | '/doctor/recipients/'
    | '/admin/monitoring/api-activity/'
    | '/admin/monitoring/authentication/'
    | '/admin/monitoring/backend/'
    | '/admin/monitoring/blockchain/'
    | '/admin/monitoring/database/'
    | '/admin/monitoring/docker/'
    | '/admin/monitoring/errors/'
    | '/admin/monitoring/frontend/'
    | '/admin/monitoring/postgresql/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/donors/$donorId'
    | '/donors/new'
    | '/recipients/$recipientId'
    | '/recipients/new'
    | '/security/$eventId'
    | '/admin'
    | '/allocation'
    | '/allocations'
    | '/blockchain'
    | '/coordinator'
    | '/doctor'
    | '/donors'
    | '/hospitals'
    | '/matching'
    | '/organs'
    | '/permissions'
    | '/recipients'
    | '/settings'
    | '/users'
    | '/allocation/matches/$matchId'
    | '/coordinator/donors/$donorId'
    | '/coordinator/donors/new'
    | '/coordinator/organs/new'
    | '/coordinator/recipients/$recipientId'
    | '/coordinator/recipients/new'
    | '/doctor/assessments/$assessmentId'
    | '/doctor/donors/$donorId'
    | '/doctor/matches/$matchId'
    | '/doctor/matching/$matchId'
    | '/doctor/organs/$organId'
    | '/doctor/recipients/$recipientId'
    | '/admin/blockchain'
    | '/admin/hospitals'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tampering'
    | '/admin/users'
    | '/allocation/history'
    | '/allocation/matches'
    | '/allocation/organs'
    | '/allocation/queue'
    | '/coordinator/allocations'
    | '/coordinator/donors'
    | '/coordinator/matching'
    | '/coordinator/organs'
    | '/coordinator/recipients'
    | '/doctor/assessments'
    | '/doctor/donors'
    | '/doctor/history'
    | '/doctor/matches'
    | '/doctor/matching'
    | '/doctor/organs'
    | '/doctor/recipients'
    | '/admin/monitoring/api-activity'
    | '/admin/monitoring/authentication'
    | '/admin/monitoring/backend'
    | '/admin/monitoring/blockchain'
    | '/admin/monitoring/database'
    | '/admin/monitoring/docker'
    | '/admin/monitoring/errors'
    | '/admin/monitoring/frontend'
    | '/admin/monitoring/postgresql'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/donors/$donorId'
    | '/_authed/donors/new'
    | '/_authed/recipients/$recipientId'
    | '/_authed/recipients/new'
    | '/_authed/security/$eventId'
    | '/_authed/admin/'
    | '/_authed/allocation/'
    | '/_authed/allocations/'
    | '/_authed/blockchain/'
    | '/_authed/coordinator/'
    | '/_authed/doctor/'
    | '/_authed/donors/'
    | '/_authed/hospitals/'
    | '/_authed/matching/'
    | '/_authed/organs/'
    | '/_authed/permissions/'
    | '/_authed/recipients/'
    | '/_authed/settings/'
    | '/_authed/users/'
    | '/_authed/allocation/matches/$matchId'
    | '/_authed/coordinator/donors/$donorId'
    | '/_authed/coordinator/donors/new'
    | '/_authed/coordinator/organs/new'
    | '/_authed/coordinator/recipients/$recipientId'
    | '/_authed/coordinator/recipients/new'
    | '/_authed/doctor/assessments/$assessmentId'
    | '/_authed/doctor/donors/$donorId'
    | '/_authed/doctor/matches/$matchId'
    | '/_authed/doctor/matching/$matchId'
    | '/_authed/doctor/organs/$organId'
    | '/_authed/doctor/recipients/$recipientId'
    | '/_authed/admin/blockchain/'
    | '/_authed/admin/hospitals/'
    | '/_authed/admin/monitoring/'
    | '/_authed/admin/roles/'
    | '/_authed/admin/settings/'
    | '/_authed/admin/tampering/'
    | '/_authed/admin/users/'
    | '/_authed/allocation/history/'
    | '/_authed/allocation/matches/'
    | '/_authed/allocation/organs/'
    | '/_authed/allocation/queue/'
    | '/_authed/coordinator/allocations/'
    | '/_authed/coordinator/donors/'
    | '/_authed/coordinator/matching/'
    | '/_authed/coordinator/organs/'
    | '/_authed/coordinator/recipients/'
    | '/_authed/doctor/assessments/'
    | '/_authed/doctor/donors/'
    | '/_authed/doctor/history/'
    | '/_authed/doctor/matches/'
    | '/_authed/doctor/matching/'
    | '/_authed/doctor/organs/'
    | '/_authed/doctor/recipients/'
    | '/_authed/admin/monitoring/api-activity/'
    | '/_authed/admin/monitoring/authentication/'
    | '/_authed/admin/monitoring/backend/'
    | '/_authed/admin/monitoring/blockchain/'
    | '/_authed/admin/monitoring/database/'
    | '/_authed/admin/monitoring/docker/'
    | '/_authed/admin/monitoring/errors/'
    | '/_authed/admin/monitoring/frontend/'
    | '/_authed/admin/monitoring/postgresql/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/': {
      id: '/_authed/allocation/'
      path: '/allocation'
      fullPath: '/allocation/'
      preLoaderRoute: typeof AuthedAllocationIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocations/': {
      id: '/_authed/allocations/'
      path: '/allocations'
      fullPath: '/allocations/'
      preLoaderRoute: typeof AuthedAllocationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/blockchain/': {
      id: '/_authed/blockchain/'
      path: '/blockchain'
      fullPath: '/blockchain/'
      preLoaderRoute: typeof AuthedBlockchainIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/': {
      id: '/_authed/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof AuthedCoordinatorIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/': {
      id: '/_authed/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthedDoctorIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/donors/': {
      id: '/_authed/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthedDonorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/donors/$donorId': {
      id: '/_authed/donors/$donorId'
      path: '/donors/$donorId'
      fullPath: '/donors/$donorId'
      preLoaderRoute: typeof AuthedDonorsDonorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/donors/new': {
      id: '/_authed/donors/new'
      path: '/donors/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof AuthedDonorsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hospitals/': {
      id: '/_authed/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof AuthedHospitalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/matching/': {
      id: '/_authed/matching/'
      path: '/matching'
      fullPath: '/matching/'
      preLoaderRoute: typeof AuthedMatchingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/organs/': {
      id: '/_authed/organs/'
      path: '/organs'
      fullPath: '/organs/'
      preLoaderRoute: typeof AuthedOrgansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permissions/': {
      id: '/_authed/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthedPermissionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipients/': {
      id: '/_authed/recipients/'
      path: '/recipients'
      fullPath: '/recipients/'
      preLoaderRoute: typeof AuthedRecipientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipients/$recipientId': {
      id: '/_authed/recipients/$recipientId'
      path: '/recipients/$recipientId'
      fullPath: '/recipients/$recipientId'
      preLoaderRoute: typeof AuthedRecipientsRecipientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipients/new': {
      id: '/_authed/recipients/new'
      path: '/recipients/new'
      fullPath: '/recipients/new'
      preLoaderRoute: typeof AuthedRecipientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/security/$eventId': {
      id: '/_authed/security/$eventId'
      path: '/security/$eventId'
      fullPath: '/security/$eventId'
      preLoaderRoute: typeof AuthedSecurityEventIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/blockchain/': {
      id: '/_authed/admin/blockchain/'
      path: '/admin/blockchain'
      fullPath: '/admin/blockchain/'
      preLoaderRoute: typeof AuthedAdminBlockchainIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/hospitals/': {
      id: '/_authed/admin/hospitals/'
      path: '/admin/hospitals'
      fullPath: '/admin/hospitals/'
      preLoaderRoute: typeof AuthedAdminHospitalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/': {
      id: '/_authed/admin/monitoring/'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring/'
      preLoaderRoute: typeof AuthedAdminMonitoringIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/roles/': {
      id: '/_authed/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AuthedAdminRolesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/settings/': {
      id: '/_authed/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tampering/': {
      id: '/_authed/admin/tampering/'
      path: '/admin/tampering'
      fullPath: '/admin/tampering/'
      preLoaderRoute: typeof AuthedAdminTamperingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/history/': {
      id: '/_authed/allocation/history/'
      path: '/allocation/history'
      fullPath: '/allocation/history/'
      preLoaderRoute: typeof AuthedAllocationHistoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/matches/': {
      id: '/_authed/allocation/matches/'
      path: '/allocation/matches'
      fullPath: '/allocation/matches/'
      preLoaderRoute: typeof AuthedAllocationMatchesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/matches/$matchId': {
      id: '/_authed/allocation/matches/$matchId'
      path: '/allocation/matches/$matchId'
      fullPath: '/allocation/matches/$matchId'
      preLoaderRoute: typeof AuthedAllocationMatchesMatchIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/organs/': {
      id: '/_authed/allocation/organs/'
      path: '/allocation/organs'
      fullPath: '/allocation/organs/'
      preLoaderRoute: typeof AuthedAllocationOrgansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/allocation/queue/': {
      id: '/_authed/allocation/queue/'
      path: '/allocation/queue'
      fullPath: '/allocation/queue/'
      preLoaderRoute: typeof AuthedAllocationQueueIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/allocations/': {
      id: '/_authed/coordinator/allocations/'
      path: '/coordinator/allocations'
      fullPath: '/coordinator/allocations/'
      preLoaderRoute: typeof AuthedCoordinatorAllocationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/donors/': {
      id: '/_authed/coordinator/donors/'
      path: '/coordinator/donors'
      fullPath: '/coordinator/donors/'
      preLoaderRoute: typeof AuthedCoordinatorDonorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/donors/$donorId': {
      id: '/_authed/coordinator/donors/$donorId'
      path: '/coordinator/donors/$donorId'
      fullPath: '/coordinator/donors/$donorId'
      preLoaderRoute: typeof AuthedCoordinatorDonorsDonorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/donors/new': {
      id: '/_authed/coordinator/donors/new'
      path: '/coordinator/donors/new'
      fullPath: '/coordinator/donors/new'
      preLoaderRoute: typeof AuthedCoordinatorDonorsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/matching/': {
      id: '/_authed/coordinator/matching/'
      path: '/coordinator/matching'
      fullPath: '/coordinator/matching/'
      preLoaderRoute: typeof AuthedCoordinatorMatchingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/organs/': {
      id: '/_authed/coordinator/organs/'
      path: '/coordinator/organs'
      fullPath: '/coordinator/organs/'
      preLoaderRoute: typeof AuthedCoordinatorOrgansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/organs/new': {
      id: '/_authed/coordinator/organs/new'
      path: '/coordinator/organs/new'
      fullPath: '/coordinator/organs/new'
      preLoaderRoute: typeof AuthedCoordinatorOrgansNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/recipients/': {
      id: '/_authed/coordinator/recipients/'
      path: '/coordinator/recipients'
      fullPath: '/coordinator/recipients/'
      preLoaderRoute: typeof AuthedCoordinatorRecipientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/recipients/$recipientId': {
      id: '/_authed/coordinator/recipients/$recipientId'
      path: '/coordinator/recipients/$recipientId'
      fullPath: '/coordinator/recipients/$recipientId'
      preLoaderRoute: typeof AuthedCoordinatorRecipientsRecipientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coordinator/recipients/new': {
      id: '/_authed/coordinator/recipients/new'
      path: '/coordinator/recipients/new'
      fullPath: '/coordinator/recipients/new'
      preLoaderRoute: typeof AuthedCoordinatorRecipientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/assessments/': {
      id: '/_authed/doctor/assessments/'
      path: '/doctor/assessments'
      fullPath: '/doctor/assessments/'
      preLoaderRoute: typeof AuthedDoctorAssessmentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/assessments/$assessmentId': {
      id: '/_authed/doctor/assessments/$assessmentId'
      path: '/doctor/assessments/$assessmentId'
      fullPath: '/doctor/assessments/$assessmentId'
      preLoaderRoute: typeof AuthedDoctorAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/donors/': {
      id: '/_authed/doctor/donors/'
      path: '/doctor/donors'
      fullPath: '/doctor/donors/'
      preLoaderRoute: typeof AuthedDoctorDonorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/donors/$donorId': {
      id: '/_authed/doctor/donors/$donorId'
      path: '/doctor/donors/$donorId'
      fullPath: '/doctor/donors/$donorId'
      preLoaderRoute: typeof AuthedDoctorDonorsDonorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/history/': {
      id: '/_authed/doctor/history/'
      path: '/doctor/history'
      fullPath: '/doctor/history/'
      preLoaderRoute: typeof AuthedDoctorHistoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/matches/': {
      id: '/_authed/doctor/matches/'
      path: '/doctor/matches'
      fullPath: '/doctor/matches/'
      preLoaderRoute: typeof AuthedDoctorMatchesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/matches/$matchId': {
      id: '/_authed/doctor/matches/$matchId'
      path: '/doctor/matches/$matchId'
      fullPath: '/doctor/matches/$matchId'
      preLoaderRoute: typeof AuthedDoctorMatchesMatchIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/matching/': {
      id: '/_authed/doctor/matching/'
      path: '/doctor/matching'
      fullPath: '/doctor/matching/'
      preLoaderRoute: typeof AuthedDoctorMatchingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/matching/$matchId': {
      id: '/_authed/doctor/matching/$matchId'
      path: '/doctor/matching/$matchId'
      fullPath: '/doctor/matching/$matchId'
      preLoaderRoute: typeof AuthedDoctorMatchingMatchIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/organs/': {
      id: '/_authed/doctor/organs/'
      path: '/doctor/organs'
      fullPath: '/doctor/organs/'
      preLoaderRoute: typeof AuthedDoctorOrgansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/organs/$organId': {
      id: '/_authed/doctor/organs/$organId'
      path: '/doctor/organs/$organId'
      fullPath: '/doctor/organs/$organId'
      preLoaderRoute: typeof AuthedDoctorOrgansOrganIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/recipients/': {
      id: '/_authed/doctor/recipients/'
      path: '/doctor/recipients'
      fullPath: '/doctor/recipients/'
      preLoaderRoute: typeof AuthedDoctorRecipientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/doctor/recipients/$recipientId': {
      id: '/_authed/doctor/recipients/$recipientId'
      path: '/doctor/recipients/$recipientId'
      fullPath: '/doctor/recipients/$recipientId'
      preLoaderRoute: typeof AuthedDoctorRecipientsRecipientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/api-activity/': {
      id: '/_authed/admin/monitoring/api-activity/'
      path: '/admin/monitoring/api-activity'
      fullPath: '/admin/monitoring/api-activity/'
      preLoaderRoute: typeof AuthedAdminMonitoringApiActivityIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/authentication/': {
      id: '/_authed/admin/monitoring/authentication/'
      path: '/admin/monitoring/authentication'
      fullPath: '/admin/monitoring/authentication/'
      preLoaderRoute: typeof AuthedAdminMonitoringAuthenticationIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/backend/': {
      id: '/_authed/admin/monitoring/backend/'
      path: '/admin/monitoring/backend'
      fullPath: '/admin/monitoring/backend/'
      preLoaderRoute: typeof AuthedAdminMonitoringBackendIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/blockchain/': {
      id: '/_authed/admin/monitoring/blockchain/'
      path: '/admin/monitoring/blockchain'
      fullPath: '/admin/monitoring/blockchain/'
      preLoaderRoute: typeof AuthedAdminMonitoringBlockchainIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/database/': {
      id: '/_authed/admin/monitoring/database/'
      path: '/admin/monitoring/database'
      fullPath: '/admin/monitoring/database/'
      preLoaderRoute: typeof AuthedAdminMonitoringDatabaseIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/docker/': {
      id: '/_authed/admin/monitoring/docker/'
      path: '/admin/monitoring/docker'
      fullPath: '/admin/monitoring/docker/'
      preLoaderRoute: typeof AuthedAdminMonitoringDockerIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/errors/': {
      id: '/_authed/admin/monitoring/errors/'
      path: '/admin/monitoring/errors'
      fullPath: '/admin/monitoring/errors/'
      preLoaderRoute: typeof AuthedAdminMonitoringErrorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/frontend/': {
      id: '/_authed/admin/monitoring/frontend/'
      path: '/admin/monitoring/frontend'
      fullPath: '/admin/monitoring/frontend/'
      preLoaderRoute: typeof AuthedAdminMonitoringFrontendIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/monitoring/postgresql/': {
      id: '/_authed/admin/monitoring/postgresql/'
      path: '/admin/monitoring/postgresql'
      fullPath: '/admin/monitoring/postgresql/'
      preLoaderRoute: typeof AuthedAdminMonitoringPostgresqlIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDonorsDonorIdRoute: typeof AuthedDonorsDonorIdRoute
  AuthedDonorsNewRoute: typeof AuthedDonorsNewRoute
  AuthedRecipientsRecipientIdRoute: typeof AuthedRecipientsRecipientIdRoute
  AuthedRecipientsNewRoute: typeof AuthedRecipientsNewRoute
  AuthedSecurityEventIdRoute: typeof AuthedSecurityEventIdRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAllocationIndexRoute: typeof AuthedAllocationIndexRoute
  AuthedAllocationsIndexRoute: typeof AuthedAllocationsIndexRoute
  AuthedBlockchainIndexRoute: typeof AuthedBlockchainIndexRoute
  AuthedCoordinatorIndexRoute: typeof AuthedCoordinatorIndexRoute
  AuthedDoctorIndexRoute: typeof AuthedDoctorIndexRoute
  AuthedDonorsIndexRoute: typeof AuthedDonorsIndexRoute
  AuthedHospitalsIndexRoute: typeof AuthedHospitalsIndexRoute
  AuthedMatchingIndexRoute: typeof AuthedMatchingIndexRoute
  AuthedOrgansIndexRoute: typeof AuthedOrgansIndexRoute
  AuthedPermissionsIndexRoute: typeof AuthedPermissionsIndexRoute
  AuthedRecipientsIndexRoute: typeof AuthedRecipientsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
  AuthedAllocationMatchesMatchIdRoute: typeof AuthedAllocationMatchesMatchIdRoute
  AuthedCoordinatorDonorsDonorIdRoute: typeof AuthedCoordinatorDonorsDonorIdRoute
  AuthedCoordinatorDonorsNewRoute: typeof AuthedCoordinatorDonorsNewRoute
  AuthedCoordinatorOrgansNewRoute: typeof AuthedCoordinatorOrgansNewRoute
  AuthedCoordinatorRecipientsRecipientIdRoute: typeof AuthedCoordinatorRecipientsRecipientIdRoute
  AuthedCoordinatorRecipientsNewRoute: typeof AuthedCoordinatorRecipientsNewRoute
  AuthedDoctorAssessmentsAssessmentIdRoute: typeof AuthedDoctorAssessmentsAssessmentIdRoute
  AuthedDoctorDonorsDonorIdRoute: typeof AuthedDoctorDonorsDonorIdRoute
  AuthedDoctorMatchesMatchIdRoute: typeof AuthedDoctorMatchesMatchIdRoute
  AuthedDoctorMatchingMatchIdRoute: typeof AuthedDoctorMatchingMatchIdRoute
  AuthedDoctorOrgansOrganIdRoute: typeof AuthedDoctorOrgansOrganIdRoute
  AuthedDoctorRecipientsRecipientIdRoute: typeof AuthedDoctorRecipientsRecipientIdRoute
  AuthedAdminBlockchainIndexRoute: typeof AuthedAdminBlockchainIndexRoute
  AuthedAdminHospitalsIndexRoute: typeof AuthedAdminHospitalsIndexRoute
  AuthedAdminMonitoringIndexRoute: typeof AuthedAdminMonitoringIndexRoute
  AuthedAdminRolesIndexRoute: typeof AuthedAdminRolesIndexRoute
  AuthedAdminSettingsIndexRoute: typeof AuthedAdminSettingsIndexRoute
  AuthedAdminTamperingIndexRoute: typeof AuthedAdminTamperingIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
  AuthedAllocationHistoryIndexRoute: typeof AuthedAllocationHistoryIndexRoute
  AuthedAllocationMatchesIndexRoute: typeof AuthedAllocationMatchesIndexRoute
  AuthedAllocationOrgansIndexRoute: typeof AuthedAllocationOrgansIndexRoute
  AuthedAllocationQueueIndexRoute: typeof AuthedAllocationQueueIndexRoute
  AuthedCoordinatorAllocationsIndexRoute: typeof AuthedCoordinatorAllocationsIndexRoute
  AuthedCoordinatorDonorsIndexRoute: typeof AuthedCoordinatorDonorsIndexRoute
  AuthedCoordinatorMatchingIndexRoute: typeof AuthedCoordinatorMatchingIndexRoute
  AuthedCoordinatorOrgansIndexRoute: typeof AuthedCoordinatorOrgansIndexRoute
  AuthedCoordinatorRecipientsIndexRoute: typeof AuthedCoordinatorRecipientsIndexRoute
  AuthedDoctorAssessmentsIndexRoute: typeof AuthedDoctorAssessmentsIndexRoute
  AuthedDoctorDonorsIndexRoute: typeof AuthedDoctorDonorsIndexRoute
  AuthedDoctorHistoryIndexRoute: typeof AuthedDoctorHistoryIndexRoute
  AuthedDoctorMatchesIndexRoute: typeof AuthedDoctorMatchesIndexRoute
  AuthedDoctorMatchingIndexRoute: typeof AuthedDoctorMatchingIndexRoute
  AuthedDoctorOrgansIndexRoute: typeof AuthedDoctorOrgansIndexRoute
  AuthedDoctorRecipientsIndexRoute: typeof AuthedDoctorRecipientsIndexRoute
  AuthedAdminMonitoringApiActivityIndexRoute: typeof AuthedAdminMonitoringApiActivityIndexRoute
  AuthedAdminMonitoringAuthenticationIndexRoute: typeof AuthedAdminMonitoringAuthenticationIndexRoute
  AuthedAdminMonitoringBackendIndexRoute: typeof AuthedAdminMonitoringBackendIndexRoute
  AuthedAdminMonitoringBlockchainIndexRoute: typeof AuthedAdminMonitoringBlockchainIndexRoute
  AuthedAdminMonitoringDatabaseIndexRoute: typeof AuthedAdminMonitoringDatabaseIndexRoute
  AuthedAdminMonitoringDockerIndexRoute: typeof AuthedAdminMonitoringDockerIndexRoute
  AuthedAdminMonitoringErrorsIndexRoute: typeof AuthedAdminMonitoringErrorsIndexRoute
  AuthedAdminMonitoringFrontendIndexRoute: typeof AuthedAdminMonitoringFrontendIndexRoute
  AuthedAdminMonitoringPostgresqlIndexRoute: typeof AuthedAdminMonitoringPostgresqlIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDonorsDonorIdRoute: AuthedDonorsDonorIdRoute,
  AuthedDonorsNewRoute: AuthedDonorsNewRoute,
  AuthedRecipientsRecipientIdRoute: AuthedRecipientsRecipientIdRoute,
  AuthedRecipientsNewRoute: AuthedRecipientsNewRoute,
  AuthedSecurityEventIdRoute: AuthedSecurityEventIdRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAllocationIndexRoute: AuthedAllocationIndexRoute,
  AuthedAllocationsIndexRoute: AuthedAllocationsIndexRoute,
  AuthedBlockchainIndexRoute: AuthedBlockchainIndexRoute,
  AuthedCoordinatorIndexRoute: AuthedCoordinatorIndexRoute,
  AuthedDoctorIndexRoute: AuthedDoctorIndexRoute,
  AuthedDonorsIndexRoute: AuthedDonorsIndexRoute,
  AuthedHospitalsIndexRoute: AuthedHospitalsIndexRoute,
  AuthedMatchingIndexRoute: AuthedMatchingIndexRoute,
  AuthedOrgansIndexRoute: AuthedOrgansIndexRoute,
  AuthedPermissionsIndexRoute: AuthedPermissionsIndexRoute,
  AuthedRecipientsIndexRoute: AuthedRecipientsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
  AuthedAllocationMatchesMatchIdRoute: AuthedAllocationMatchesMatchIdRoute,
  AuthedCoordinatorDonorsDonorIdRoute: AuthedCoordinatorDonorsDonorIdRoute,
  AuthedCoordinatorDonorsNewRoute: AuthedCoordinatorDonorsNewRoute,
  AuthedCoordinatorOrgansNewRoute: AuthedCoordinatorOrgansNewRoute,
  AuthedCoordinatorRecipientsRecipientIdRoute:
    AuthedCoordinatorRecipientsRecipientIdRoute,
  AuthedCoordinatorRecipientsNewRoute: AuthedCoordinatorRecipientsNewRoute,
  AuthedDoctorAssessmentsAssessmentIdRoute:
    AuthedDoctorAssessmentsAssessmentIdRoute,
  AuthedDoctorDonorsDonorIdRoute: AuthedDoctorDonorsDonorIdRoute,
  AuthedDoctorMatchesMatchIdRoute: AuthedDoctorMatchesMatchIdRoute,
  AuthedDoctorMatchingMatchIdRoute: AuthedDoctorMatchingMatchIdRoute,
  AuthedDoctorOrgansOrganIdRoute: AuthedDoctorOrgansOrganIdRoute,
  AuthedDoctorRecipientsRecipientIdRoute:
    AuthedDoctorRecipientsRecipientIdRoute,
  AuthedAdminBlockchainIndexRoute: AuthedAdminBlockchainIndexRoute,
  AuthedAdminHospitalsIndexRoute: AuthedAdminHospitalsIndexRoute,
  AuthedAdminMonitoringIndexRoute: AuthedAdminMonitoringIndexRoute,
  AuthedAdminRolesIndexRoute: AuthedAdminRolesIndexRoute,
  AuthedAdminSettingsIndexRoute: AuthedAdminSettingsIndexRoute,
  AuthedAdminTamperingIndexRoute: AuthedAdminTamperingIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
  AuthedAllocationHistoryIndexRoute: AuthedAllocationHistoryIndexRoute,
  AuthedAllocationMatchesIndexRoute: AuthedAllocationMatchesIndexRoute,
  AuthedAllocationOrgansIndexRoute: AuthedAllocationOrgansIndexRoute,
  AuthedAllocationQueueIndexRoute: AuthedAllocationQueueIndexRoute,
  AuthedCoordinatorAllocationsIndexRoute:
    AuthedCoordinatorAllocationsIndexRoute,
  AuthedCoordinatorDonorsIndexRoute: AuthedCoordinatorDonorsIndexRoute,
  AuthedCoordinatorMatchingIndexRoute: AuthedCoordinatorMatchingIndexRoute,
  AuthedCoordinatorOrgansIndexRoute: AuthedCoordinatorOrgansIndexRoute,
  AuthedCoordinatorRecipientsIndexRoute: AuthedCoordinatorRecipientsIndexRoute,
  AuthedDoctorAssessmentsIndexRoute: AuthedDoctorAssessmentsIndexRoute,
  AuthedDoctorDonorsIndexRoute: AuthedDoctorDonorsIndexRoute,
  AuthedDoctorHistoryIndexRoute: AuthedDoctorHistoryIndexRoute,
  AuthedDoctorMatchesIndexRoute: AuthedDoctorMatchesIndexRoute,
  AuthedDoctorMatchingIndexRoute: AuthedDoctorMatchingIndexRoute,
  AuthedDoctorOrgansIndexRoute: AuthedDoctorOrgansIndexRoute,
  AuthedDoctorRecipientsIndexRoute: AuthedDoctorRecipientsIndexRoute,
  AuthedAdminMonitoringApiActivityIndexRoute:
    AuthedAdminMonitoringApiActivityIndexRoute,
  AuthedAdminMonitoringAuthenticationIndexRoute:
    AuthedAdminMonitoringAuthenticationIndexRoute,
  AuthedAdminMonitoringBackendIndexRoute:
    AuthedAdminMonitoringBackendIndexRoute,
  AuthedAdminMonitoringBlockchainIndexRoute:
    AuthedAdminMonitoringBlockchainIndexRoute,
  AuthedAdminMonitoringDatabaseIndexRoute:
    AuthedAdminMonitoringDatabaseIndexRoute,
  AuthedAdminMonitoringDockerIndexRoute: AuthedAdminMonitoringDockerIndexRoute,
  AuthedAdminMonitoringErrorsIndexRoute: AuthedAdminMonitoringErrorsIndexRoute,
  AuthedAdminMonitoringFrontendIndexRoute:
    AuthedAdminMonitoringFrontendIndexRoute,
  AuthedAdminMonitoringPostgresqlIndexRoute:
    AuthedAdminMonitoringPostgresqlIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
